### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by seagreen** [mitchellwrosen/termbox-banana#2]
Problem here:
```
isKeyEsc :: Termbox.Event -> Bool
isKeyEsc = \case
  Termbox.EventKey Termbox.KeyEsc _ -> True
  _ -> False
```
`Termbox.EventKey` only takes one argument.

**Comment by mitchellwrosen** [comment]
Oh boy, a user! :)

Thanks - I thought I fixed the problem - you can see the new docs uploaded here under this useless "candidate" variant: https://hackage.haskell.org/package/termbox-banana-0.3.1/candidate/docs/Termbox-Banana.html

I'm still working on uploading the non-candidate docs. `cabal upload --documentation --publish` just... doesn't... work? so I'll leave this open until I can figure that out. :sweat:

**Comment by mitchellwrosen** [comment]
The deed is done
